name: music_melody
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  cloud_firestore: ^4.13.6
  dio: ^5.4.0
  file_picker: ^6.1.1
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  gallery_saver: ^2.3.2
  get: ^4.6.6
  google_nav_bar: ^5.0.6
  image_picker: ^1.0.5
  just_audio: ^0.9.36
  line_icons: ^2.0.3
  on_audio_query: ^2.9.0
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
